name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.7'

      - name: Set up Xcode for iOS
        run: |
          sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Build and test for iOS
        run: |
          # Set the target platform to iOS
          swift test --platform iOS


